// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tefwjaepmnngohdphydq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZndqYWVwbW5uZ29oZHBoeWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDkwNzAsImV4cCI6MjA3MzYyNTA3MH0.G2D5cHJtOmSSKn_uYMbFuf-IMC2yZp6WmIYAPLxTHtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});